build:
  nodes:
    coverage:
      tests:
        override:
          - command: composer test
            coverage:
              file: tests/coverage.xml   # <- Set this to where we find the coverage data.
                                          #    The path is relative to the current directory.
              format: clover
