name: Run tests

on:
  push:
  schedule:
    - cron: '0 0 * * *'

jobs:
  php-tests:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        php: [ 8.0, 8.1, 8.2, 7.4 ]
        laravel: [ 10.*, 9.*, 8.* , 7.* , 6.* ]
        dependency-version: [prefer-stable ]
        os: [ ubuntu-latest ]
        include:
          - laravel: 10.*
            testbench: 8.*
            database: 8.0.x-dev
          - laravel: 9.*
            testbench: 7.*
            database: 7.0.x-dev
          - laravel: 8.*
            testbench: 6.*
            database: 6.x-dev
          - laravel: 7.*
            testbench: 5.*
            database: 5.*
          - laravel: 6.*
            testbench: 4.*
            database: 4.*
        exclude:
          - laravel: 6.*
            php: 8.0
          - laravel: 6.*
            php: 8.1
          - laravel: 6.*
            php: 8.2
          - laravel: 7.*
            php: 8.0
          - laravel: 7.*
            php: 8.1
          - laravel: 7.*
            php: 8.2
          - laravel: 5.8.*
            php: 8.0
          - laravel: 5.8.*
            php: 8.1
          - laravel: 5.8.*
            php: 8.2
          - laravel: 9.*
            php: 7.4
          - laravel: 10.*
            php: 7.4
          - laravel: 10.*
            php: 8.0
          - laravel: 8.*
            dependency-version: prefer-lowest


    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.dependency-version }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
          composer update --${{ matrix.dependency-version }} --prefer-dist --no-interaction --no-suggest

      - name: Execute tests
        run: vendor/bin/phpunit
